server:
  port: 8000
  error:
    include-message: always

app:
  product:
    host: localhost
    port: 8001
  recommendation:
    host: localhost
    port: 8002
  review:
    host: localhost
    port: 8003

logging:
  level:
    root: INFO
    msa.lime1st: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  product:
    host: product
    port: 8080
  recommendation:
    host: recommendation
    port: 8080
  review:
    host: review
    port: 8080