server:
  port: 8000
  error:
    include-message: always

app:
  product:
    host: localhost
    port: 8001
  recommendation:
    host: localhost
    port: 8002
  review:
    host: localhost
    port: 8003

logging:
  level:
    root: INFO
    msa.lime1st: DEBUG