server:
  port: 8002
  error:
    include-message: always

spring:
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: recommendation-db

logging:
  level:
    root: info
    msa.lime1st: debug
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      host: mongodb

server:
  port: 8080