server:
  port: 8003
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    msa.lime1st: debug
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql/review-db

server:
  port: 8080