spring.config.import: "configserver:"

spring:
  application.name: authorization
  cloud.config:
    failFast: false
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: ${CONFIG_SERVER_URI:http://localhost:8888}
    username: ${CONFIG_SERVER_USR}
    password: ${CONFIG_SERVER_PWD}